### ISSUE TITLE
PI generated

### ISSUE THREAD

**Issue by aremazeilles** [dzhvansky/pepato#14]
Looking at the generated PI, we see 11 files:

```term
╭─anthony@PRT0962AL ~/code/eurobench/pepato ‹octave_version*› 
╰─$ ls test_data/output 
subject_0_run_0_emg_reco_quality.yaml                   subject_0_run_0_muscle_synergy_number.yaml
subject_0_run_0_matching_standard_reference_index.yaml  subject_0_run_0_pattern_coa.yaml
subject_0_run_0_motor_pool_coact_index.yaml             subject_0_run_0_pattern_fwhm.yaml
subject_0_run_0_motor_pool_fwhm.yaml                    subject_0_run_0_patterns_similarity.yaml
subject_0_run_0_motor_pool_max_activation.yaml          subject_0_run_0_synergies_similarity.yaml
subject_0_run_0_motor_pool_similarity.yaml
```

The excel template sheet only contain 6:

```term
PI: muscle_synergy_number output: vector
PI: emg_reconstruction_quality output: vector
PI: pattern_fwhm output: vector_of_vector
PI: pattern_coa output: vector_of_vector
PI: muscle_module_similarity output: vector_of_matrix
PI: matching_standard_reference_index output: vector_of_matrix
```
Could you update the template sheet with the missing PI?

@alfonsotecnalia is it ok to have `subject_0_run_0` at the beginning of the PI file names?

**Comment by dzhvansky** [comment]
I don't really understand why not all PIs are in the excel template.
In the last version that I saw, there were both muscle synergies PIs and spinal maps PIs. But your indicator list contains only muscle synergies PIs.

**Comment by dzhvansky** [comment]
Please check the excel, if there really are not all PIs, we will send the latest version again.

**Comment by aremazeilles** [comment]
I am looking at file: https://docs.google.com/spreadsheets/d/19HB6j2O9O_58Vs_J8xOiOlo_4o82bRgQ/edit#gid=1788698095

I effectively see more PI, my mistakes:

```
muscle_synergy_number
emg_reconstruction_quality
pattern_fwhm
pattern_coa
muscle_module_similarity
matching_standard_reference_index
motor_pool_max_activation_timing
motor_pool_fwhm
motor_pool_coactivation
motor_pool_similarity
```
10 PIs. But the generated files are 11:

```term
╭─anthony@PRT0962AL ~/code/eurobench/pepato ‹octave_version*› 
╰─$ ls output
subject_0_run_0_emg_reco_quality.yaml
subject_0_run_0_matching_standard_reference_index.yaml
subject_0_run_0_motor_pool_coact_index.yaml
subject_0_run_0_motor_pool_fwhm.yaml
subject_0_run_0_motor_pool_max_activation.yaml
subject_0_run_0_motor_pool_similarity.yaml
subject_0_run_0_muscle_synergy_number.yaml
subject_0_run_0_pattern_coa.yaml
subject_0_run_0_pattern_fwhm.yaml
subject_0_run_0_patterns_similarity.yaml
subject_0_run_0_synergies_similarity.yaml
```

If I look for correspondance yaml file -> PI name, I get:

```yaml

subject_0_run_0_emg_reco_quality.yaml: emg_reconstruction_quality
subject_0_run_0_matching_standard_reference_index.yaml: matching_standard_reference_index
subject_0_run_0_motor_pool_coact_index.yaml: motor_pool_coactivation
subject_0_run_0_motor_pool_fwhm.yaml: motor_pool_fwhm
subject_0_run_0_motor_pool_max_activation.yaml: motor_pool_max_activation_timing
subject_0_run_0_motor_pool_similarity.yaml: motor_pool_similarity
subject_0_run_0_muscle_synergy_number.yaml: muscle_synergy_number
subject_0_run_0_pattern_coa.yaml: pattern_coa
subject_0_run_0_pattern_fwhm.yaml: pattern_fwhm
subject_0_run_0_patterns_similarity.yaml: 
subject_0_run_0_synergies_similarity.yaml: 
# PI named muscle_module_similarity unasigned to a yaml file
```

So I have the impression the two last yaml files are not associated to a PI from the excel sheet, and I don't see the to which file the PI named `muscle_module_similarity` should be assigned to.
