### ISSUE TITLE
Eurobench input format.

### ISSUE THREAD

**Issue by aremazeilles** [dzhvansky/pepato#22]
Right now the input format we are using in the Eurobench platform is indicated [here](https://github.com/dzhvansky/pepato/tree/octave_version#usage)

```term
>>> ./run_pepato left BLF db_healthy_adults_8m ./test_data/input/subject_0_run_0_emg_speed2kmh.csv ./test_data/input/subject_0_run_0_gaitEvents_speed2kmh.yaml ./test_data/input/subject_0_run_0_emg_speed4kmh.csv ./test_data/input/subject_0_run_0_gaitEvents_speed4kmh.yaml ./test_data/input/subject_0_run_0_emg_speed6kmh.csv ./test_data/input/subject_0_run_0_gaitEvents_speed6kmh.yaml ./test_data
```

Meaning that we can only compute metrics if we have data for 2kmh, 4kmh __and__ 6kmh.
And, actually, even your [Elderly dataset](https://drive.google.com/drive/folders/15cVVWc94BTvL7gQ91rKhWGNZSh_-HD8i) could not be used, as it only contains 2 and 4kmh data.

We are wondering if we could not simplify it, and enable metric computation even with a unique velocity. It seems the 3 velocities could not be achieved systematically at the Madrid facility. I have also been told that there they could use the metric with a single velocity, so that it would be great to have the same feature for the online version.

What do you think ?

**Comment by dzhvansky** [comment]
Totally agree with you. Fortunately, the ability to use a random file order and/or incomplete velocity set was implemented earlier. The last commit slightly changed the structure of the output yaml files (in case of incomplete velocity set). This is how it looks in the case of using only single speed data:
```
type: vector_of_vector
label: [NaN, NaN, speed6kmh]
value:
  - label: [module_a]
    value: [NaN]
  - label: [module_a]
    value: [NaN]
  - label: [module_a, module_b, module_c, module_d, module_e]
    value: [NaN, 2, NaN, 4, 3]
```
Please note that normalization is carried out based on all velocities, so if even one file is excluded, the PIs may change (comparing with 3-speed based computation).
