### ISSUE TITLE
pi output type

### ISSUE THREAD

**Issue by alfonsotecnalia** [dzhvansky/pepato#8]
At this moment, we are considering the following [output types](https://github.com/aremazeilles/eurobench_documentation/blob/master/pi_spec.adoc#32-output-data): scalar, vector, matrix, labelled_matrix and string.

We see in the output file that you are considering output types such as vector_of_vector and vector_of_matricies. Could they be considered as a matrices (type matrix)? Would there be any reason to add vector_of_vector/vector_of_matrices types to the list of accepted output types?

**Comment by aremazeilles** [comment]
You are right,, it should be `value` and not `values`. 
Your proposition for adding a label item sounds good to me as well.

 This is unclear where there is 3 spaces and not 2. Could you clarify this?

**Comment by dzhvansky** [comment]
> This is unclear where there is 3 spaces and not 2. Could you clarify this?

I mean there is one extra space before the hyphen in `- label` keys:
![image](https://user-images.githubusercontent.com/47847143/102224100-96559480-3ef6-11eb-8ccf-a0d0a5105a7b.png)

What I suggest (common yaml format):
![image](https://user-images.githubusercontent.com/47847143/102224925-9f933100-3ef7-11eb-80a6-8a6198b1fdd6.png)


And the last question is whether quotes are needed for string variables in our output yaml format?

**Comment by aremazeilles** [comment]
In this [documentation](https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html), they are suggesting to add an indentation.

Actually I am using in the [cI process](https://github.com/dzhvansky/pepato/blob/octave_version/.github/workflows/linting.yml#L23) [yamllint](https://yamllint.readthedocs.io/en/stable/) to verify all yaml file in the repository. If I launch it with your suggestion:

```yaml
type: 'vector_of_vector'
values:
- label: [label_1, label_2]
  value: [val_1, val_2]
- label: [label_1, label_2, label_3]
  value: [val_1, val_2, val_3]
```
It states:

```term
╭─anthony@PRT0962AL ~/tmo 
╰─$ yamllint pi.yaml
pi.yaml
  1:1       warning  missing document start "---"  (document-start)
  3:1       error    wrong indentation: expected 2 but found 0  (indentation)
```
Note that under python, loading of both versions works, and it is probable that both version works. But as I use yamlint I would be more in favour in having an indentation, as we suggest.
Actually there might be a differentiation whether the list is at the root of the yaml file (in that case, no indentation) or whether the list is associated to a key (which is our case).

> And the last question is whether quotes are needed for string variables in our output yaml format?

I would say that this is not mandatory

**Comment by aremazeilles** [comment]
Actually to respect the yamllint indication, we should even go for an indentation of two spaces:

```yaml
type: 'vector_of_vector'
value:
  - label: [label_1, label_2]
    value: [val_1, val_2]
  - label: [label_1, label_2, label_3]
    value: [val_1, val_2, val_3]
```

But the tool seems to accept indentation of one space, so I think we are flexible in that, whether you use 1 or 2 space indentation
